# The below lines tells pytest that the settings below belongs to Pytest
[pytest]

# Whatever you put here = automatically applied when you run:
addopts =
    # ----------------------------------
    #   General Options
    # ----------------------------------
    -v
    --browser=chromium
;    --browser=firefox
;    --browser=webkit
    --headed
    --base-url=http://localhost/opencart-4.1.0.3/upload/

    # ----------------------------------
    #   Captures and Reports (Debugging)
    # ----------------------------------

    # Capture the video whenever a failure happens
    --video=retain-on-failure
    # Capture the video every time even if it is passed or failed
    #--video=on
    #--video=off

    # Capture the screenshot whenever a failure happens
    --screenshot=only-on-failure
    # Capture the screenshot every time even if it is passed or failed
    #--screenshot=on
    #--screenshot=off

    # Capture the tracing whenever a failure happens
    --tracing=retain-on-failure
    # Capture the tracing every time even if it is passed or failed
    #--tracing=on
    #--tracing=off

    # We dont prefer HTML reports much in practical as it is very basic
    --html=reports/myreports.html --self-contained-html --capture=tee-sys
    # We mostly prefer Allure report in practical
    --alluredir=reports/allure-results

    # ----------------------------------
    #   Parallel Execution : Run tests in parallel
    # ----------------------------------
    #-n=1
    #--numprocesses=2 # its same as -n=2, Runs tests in 2 parallel processes

    # ----------------------------------
    #   Test Grouping
    # ----------------------------------
    # Use one of the beelow commands when running pytest
    # Runs only test maked as '@pytest.mark.sanity'
;    -m "sanity"
;    -m "regression"
    # Run tests that have either sanity, or regression or both. Include anything that has at least one of them
;    -m "sanity or regression"
;    -m "sanity and regression"
;    -m "sanity and not regression"
;    -m "regression and not sanity"
;
;    -m "datadriven"
;    -m "end_to_end"

    # ----------------------------------
    #   Flaky Test Handling
    # ----------------------------------
    # If test fails, retry  2 times, wait 2 seconds between retries
;    --reruns 2
;    --reruns-delay 2

# ----------------------------------
#   Custom Markers
# ----------------------------------
# Register markers to avoid warnings as discussed in Pytest session
markers =
    sanity                                  # Marks a sanity test (basic quick check)
    regression                              # Marks a regression test (full end-to-end validation)
    datadriven                              # Marks a datadriven test
    end-to-end                              # Marks end-to-end test




